version: '3.8'

services:
  react-app:
    build:
      context: . # Ścieżka do katalogu z Dockerfile
      dockerfile: Dockerfile
      args:
        IMAGE_NAME: ${FRONTEND_IMAGE} # Przekazanie ARG IMAGE_NAME
    ports:
      - ${VITE_PORT}:${VITE_PORT}
    environment:
      - NODE_ENV=production
      - VITE_PORT=${VITE_PORT}
    restart: unless-stopped
