name: Deploy to Raspberry Pi

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Test ping to Raspberry Pi
      run: ping 100.100.55.105

    - name: Deploy to Raspberry Pi
      uses: appleboy/ssh-action@v1.2.0
      with:
        host: 100.100.55.105
        username: wojtek
        port: 22
        key: ${{ secrets.PI_SSH_KEY }}
        debug: true
        script: |
          echo "Connected successfully."
          cd ${{ secrets.PI_PROJECT_PATH }}
          docker-compose down
          git pull
          docker-compose up --build -d
