name: Deploy to Raspberry Pi

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: CHECK 1
        run: pwd

      - name: CHECK 2
        run: ls -lsa

      - name: Docker Compose Down
        run: docker compose down

      - name: Git Pull
        run: git pull

      - name: Docker Compose Pull
        run: docker compose pull

      - name: Docker Compose Up
        run: docker compose up -d --build
